### ISSUE TITLE
我用的是 R61503U 的tft， 你也是用的这个吗？

### ISSUE THREAD

**Issue by buzai** [nemuisan/STM32Primer2_GPS_Tracker#1]
我看到你的代码里面有使用到 R61503U 请问你是使用的这个主控的tft吗？ 我想在树莓派上使用这个tft，
请问我应该怎么移植呢？如果可以指点一下就太感谢了

I see you use R61503U , you use this R61503U~tft ? how i can change it to raspberry?
thank you very much...

**Comment by nemuisan** [comment]
Dear buzai,

R61503 driver(i8080 bus type) is found on my FatFs example for STM32F4.
http://nemuisan.blog.bai.ne.jp/?eid=192848#STM32F4

R61503 driver is below directory in the FatFs example archive.
./lib/display/drivers/src/r61503u.c

You can easily migrarte to raspberry.

Nemui.

**Comment by buzai** [comment]
非常感谢您。
