### ISSUE TITLE
FAT SDIO Driver DMA Timeout Failure

### ISSUE THREAD

**Issue by WGR7** [nemuisan/STM32Primer2_GPS_Tracker#2]
Hi,

I'm trying to use your FAT SDIO driver with a STM32f103RC using DMA_MODE, but in when the SD_ReadBlock tries do a transfer with DMA, I'm getting a SD_DATA_TIMEOUT error. Did you test this SDIO driver with DMA? 

Here I'm getting the timeout error
while ((SD_DMAEndOfTransferStatus() == RESET) && (TransferEnd == 0) && (TransferError == SD_OK))
	{}
	if (TransferError != SD_OK)
	{
		return(TransferError);
	}

When I use pooling mode, I have sucess mounting and using File System.

Regards

**Comment by nemuisan** [comment]
Dear Wagner Batista,

Signal integlity(e.g. wirlings between MCU and SDCard) strongly affects  SDIO Transfer stabilities.
You may need reduce SDIO Clock into 12MHz(same clock speed for Polling Mode).
